### PR TITLE
Drop Python 2.6 and 3.4, use GitHub actions, fix build

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@jaraco, could you please also create a token `pypi_token` so we can deploy on PyPI? Thanks!

**Comment by jaraco** [comment]
You bet, although lately I've been migrating away from Travis to Azure Pipelines because Travis doesn't support PyPI tokens except in environment variables for some projects.

It is done. `TWINE_PASSWORD` is now set my PyPI token.

**Comment by jaraco** [comment]
Oh, whoops. You meant Github Actions. Let me figure out how to do that.

**Comment by jaraco** [comment]
token added to Github Actions

**Comment by nicoddemus** [comment]
Yeah, sorry about that, I should have been more specific. 👍

**Pull request merged**
