### PR TITLE
more popen options

### PR DESCRIPTION
**Pull request by pizzapanther**
for Popen it's nice to use `shell=True` sometimes or other Popen kwargs. So I made a way to pass in custom kwargs.

### CODE REVIEW

**Review by northernSage — CHANGES_REQUESTED** [review]
Thanks for your contribution @pizzapanther. The idea of giving the user more control over the [`Popen constructor`](https://docs.python.org/3/library/subprocess.html#popen-constructor) is definetly interesting, but passing extra starting parameters through [`XProcess.ensure`](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L107) seems a bit against the general flow of pytest-xprocess where we use [`XProcessStarter`](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L193) to customize the process startup. I think it would be more natural to add an extra class variable to [`XProcessStarter`](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L193) which then could be used to pass in the aditional keywords to `Popen` (same idea of `timeout `or `env`). Also, it would be great to have this new feature documented (just a few lines in the [README.md](https://github.com/pytest-dev/pytest-xprocess/blob/master/README.rst) file) and add a test as well.

Again, thanks for your contribution 👍🏻

**Comment by pizzapanther** [comment]
Sounds good, I was debating whether to go that route or not. I'll refactor and have an update. Thanks for the feedback.

**Comment by northernSage** [comment]
I have updated the PR and made the few adjustments discussed previously, namely:

- add a new [popen_kwargs](https://github.com/pytest-dev/pytest-xprocess/pull/60/files#diff-6f88d574169a6438b98ab7de67fbe2ef6b311c09cf4c49db9a7ef652d7f61d0fR239) variable used for passing keywords to the [Popen constructor.](https://github.com/pytest-dev/pytest-xprocess/pull/60/files#diff-6f88d574169a6438b98ab7de67fbe2ef6b311c09cf4c49db9a7ef652d7f61d0fR170)
- add a [test case](https://github.com/pytest-dev/pytest-xprocess/pull/60/files#diff-bd351db71dc77f95e04115348ca9e4f32fe4da1f4e10710edffccf4802bb0a8cR93) for the new feature

Tests are failing for py3.6 and older since, apparently, the alias `text_mode` used in the tests has been added only at py3.7. I'll fix this in the next few days.

I wonder if [ProcessStarter.env](https://github.com/pytest-dev/pytest-xprocess/blob/master/xprocess.py#L218) is still necessary. I'm considering passing `env` values using `popen_kwargs` too. A second opinion on this would be nice, WDYT @nicoddemus ?

**Comment by northernSage** [comment]
On second thought, we should probably keep `env` for compatibility reasons 🤔

**Comment by northernSage** [comment]
Thanks for your contribution @pizzapanther !

**Comment by pizzapanther** [comment]
totally dropped off the map before I finished this. Glad to see it made it in. Thanks for pushing it over the line.

**Pull request merged**
