### PR TITLE
Remove deprecated XProcessInfo.kill method and related test

### PR DESCRIPTION
**Pull request by northernSage**

### CODE REVIEW

**Review by nicoddemus — CHANGES_REQUESTED** [review]
Looks good, just missing a changelog entry. 👍

**Comment by northernSage** [comment]
> Looks good, just missing a changelog entry. 👍

Yes, I was considering making this a patch (0.14.1). But I wonder if we should already start the next minor release (0.15.0) since we'll have more considerable changes from #21  soon. WDYT? @nicoddemus

**Comment by nicoddemus** [comment]
> Yes, I was considering making this a patch (0.14.1).

Actually according to semantic versioning, removing functionality should be done only in major releases. However given that `pytest-xprocess` is in version 0.x, the usual approach is to use minor releases for that. For this reason I believe this should go into 0.15 only. 👍

**Comment by northernSage** [comment]
Oh, I see. thanks.

**Comment by nicoddemus** [comment]
Thanks!

**Pull request merged**
