### PR TITLE
Test suite refactor

### PR DESCRIPTION
**Pull request by northernSage**
As of now we have some repeated code in our test suite and coverage is under 100%, this PR aims to solve both issues.

- [x] separate `tests` and `example` directories
~abstract repeated code into a parent `BaseTest` class~(ended up using `pytest.mark.parametrize` for this)
- [x] remove deprecated CompatStarter
- [x] break tests down into multiple modules
- [x] extend tests to reach 100% cov
- [x] update tox.ini `[testenv]`
- [x] look into potential compatibility problem with windows and SIGTERM handler in `server.py`
- [x] clean up

I'm also considering replacing  `example` with a `docs` dir containing not only examples but general documentation for `pytest-xprocess`, maybe using something like [sphinx](https://www.sphinx-doc.org/en/master/) (most likely in a separate PR)?

### CODE REVIEW

**Comment by northernSage** [comment]
Some context on the changes made so far:

- `xprocess.CompatStarter` has been around since [0.12.0](https://github.com/pytest-dev/pytest-xprocess/blob/master/CHANGELOG.rst#0120-2017-06-06) when legacy starter functions were deprecated in favour of `xprocess.ProcessStarter`. I took the chance to remove it and adjust the tests to account for that.

- [xprocess.py line 50](https://github.com/pytest-dev/pytest-xprocess/blob/e8e9494e0cc65f69775d47525bd5b1caba580623/xprocess.py#L50) and [xprocess.py line 53](https://github.com/pytest-dev/pytest-xprocess/blob/e8e9494e0cc65f69775d47525bd5b1caba580623/xprocess.py#L53) are some interesting wholes in our coverage. The first block is only executed when a process fails termination with `SIGTERM` and the second when both `SIGTERM` and `SIGKILL` fail. The way I came up to test the first branch (line 50) was making [server.py](https://github.com/northernSage/pytest-xprocess/blob/refac-test-suite/tests/server.py) take command line arguments to optionally spawn children processes that ignore `SIGTERM` through a custom [handler function](https://github.com/northernSage/pytest-xprocess/blob/e8e9494e0cc65f69775d47525bd5b1caba580623/tests/server.py#L70), thus artificially creating a scenario where termination with `SIGTERM` "_fails_" and times out. Now we can easily write a test for this:

    ```python
    @pytest.mark.parametrize("port,proc_name", [(6777, "s1"), (6778, "s2")])
    def test_sigkill_after_failed_sigterm(self, port, proc_name):
        # explicitly tell xprocess_starter fixture to make
        # server instance ignore SIGTERM
        self.start_server("started", proc_name, port, ignore_sigterm=True)
        # since terminate with sigterm will fail, set a lower
        # timeout before sending sigkill so tests won't take too long
        assert self.terminate(proc_name, timeout=1) == 1
    ```

  Unfortunately, I could not use the same approach for [xprocess.py line 53](https://github.com/pytest-dev/pytest-xprocess/blob/e8e9494e0cc65f69775d47525bd5b1caba580623/xprocess.py#L53) since, by definition, [SIGKILL](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGKILL):
  > cannot be caught or ignored, and the receiving process cannot perform any clean-up upon receiving this signal

  so I have used `# pragma: no cover` to skip this branch when running coverage given I'm not sure how to go about this (open to suggestions here).

**Comment by northernSage** [comment]
Hm, win32 builds are hanging on CI for some reason. This is annoying since I'm not on windows to debug. I'll have to keep using GitHub C.I to test until I find what is causing this... :bowtie:

**Comment by northernSage** [comment]
There we go. Apparently it was a stream problem since writing the match patterns to `sys.stderr` seem to have solved it.

**Comment by northernSage** [comment]
Considering the amount of changes this PR proposes I thought it would be better to open this for review before going any further.

At the moment our coverage looks like:
```
pytest_xprocess.py -------------- 96% cov
xprocess.py --------------------- 99% cov
```
We don't have 100% yet due to the following pieces:

```python
# xprocess.py
def filter_lines(self, lines): 
    non_empty_lines = (x for x in lines if x.strip())  # <<< this line
    return itertools.islice(non_empty_lines, 50)
```

```python
# pytest_xprocess.pytest_runtest_makereport
if hasattr(longrepr, "addsection"):
    longrepr.addsection("%s log" % name, content)  # <<< this line
```
The generator in the first snippet naturally doesn't finish once only the first 50 non-empty lines are checked. PR #21 will change how this is handled so I'm considering tackling this particular issue after merging #21. 

Regarding the second snippet, I'm not sure how we should test this so a second opinion would be welcome.

**Comment by nicoddemus** [comment]
I will try to review this in the next few days, but I really don't even know the current test suite so my contributions here might be limited. If you have specific points you would like my opinion, feel free to point them out! 👍 


But if this is blocking you, I trust your judgment to go ahead and merge this.

**Comment by northernSage** [comment]
Don't worry about it, take your time. I'm working on this in parallel and extending/adjusting the tests as new features are implemented so this is not blocking me at all. I still have to update the PR for 0.16.0 and I plan to test it thoroughly so we don't end up with a flaky suite. I just requested a review for my own peace of mind :grimacing:

**Comment by northernSage** [comment]
Just an update, our coverage is now:
```
pytest_xprocess.py -------------- 96% cov
xprocess.py --------------------- 100% cov
total ----------------------------- 99% cov
```

**Comment by nicoddemus** [comment]
@northernSage feel free to go ahead and merge this if this is good enough on your eyes; I don't know the original test suite anyways, and I fully trust your instincts here. 👍

**Comment by northernSage** [comment]
Alright, I'll update this to `0.17.0` and try to merge it before the next release 👍🏻

**Comment by northernSage** [comment]
While solving the conflicts for `0.17.0` I noticed the suite was getting more complex than I would like so I ended up changing things around a bit and it's much simpler now. I also added a few more shields to `README.md` (some more neat visual info on the project won't hurt I suppose). With that we have 100% cov and I think we are good for our next release 🎉

**Pull request merged**
